export const EDIT_SYNONYM = 'EDIT_SYNONYM';

export const SET_IS_EDITING = 'SET_IS_EDITING';

export const DELETE_SYNONYM = 'DELETE_SYNONYM';

export const SET_SYNONYM_FOR_DELETE = 'SET_SYNONYM_FOR_DELETE';

export const ADD_SYNONYM = 'ADD_SYNONYM';

export const CLEAR_SYNONYMS = 'CLEAR_SYNONYMS';